version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: sh -c "apt-get update && apt-get install -y netcat && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend/public:/app/public
  #   ports:
  #     - "3000:3000"

volumes:
  postgres_data:
